# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Allergy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Allergy
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'BRYXBanner', '~> 0.7'
  pod 'SQLite.swift', '~> 0.11.4'

end
