# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATXPollen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ATXPollen
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Charts'

end
