# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Pollen' do
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'BRYXBanner', '~> 0.7'
end
